### ISSUE TITLE
Datashader integration TODO

### ISSUE THREAD

**Issue by jonmmease** [jonmmease/hilbert_frame#3]
The decision has been made to move this class into the core Datashader project in the coming month. Until a PR is ready on the datashader project, this issue will hold a checklist of integration items.

 - [x] Convert pickle file to parquet metadata if possible, and if not possible then to JSON/YAML.  This will likely involve reconstructing the partition and distance grids from the partition division information. (https://github.com/jonmmease/hilbert_frame/issues/2)

 - [x] Evaluate the feasibility of avoiding saving the distance values in the parquet files (https://github.com/jonmmease/hilbert_frame/issues/1)

 - [ ] Add Numpy-style docstrings everywhere

 - [ ] Condense example notebooks and convert into datashader documentation.  To said documentation, add some general guidance for selecting reasonable values for the `p` and `npartitions` parameters.
